### ISSUE TITLE
Unhandled exception if an empty feed url is found

### ISSUE THREAD

**Issue by tominbrighton** [cakuki/feed-finder#1]
When trying to find feeds on pages such as http://www.ksta.de, an unhandled exception is thrown:

Sample code:

```
var feedFinder = require('feed-finder');

feedFinder('http://www.ksta.de', function (err, feedUrls) {
  console.log(feedUrls);
});
```

Output:

```
$ node sample.js
url.js:73
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url);
    ^

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:73:11)
    at urlParse (url.js:67:5)
    at Url.resolve (url.js:621:29)
    at Object.urlResolve [as resolve] (url.js:617:40)
    at isFeedLink (/Users/thomasm/brandwatch/mission-control/node_modules/feed-finder/lib/parser.js:65:20)
    at Object.onOpenTag (/Users/thomasm/brandwatch/mission-control/node_modules/feed-finder/lib/parser.js:39:28)
    at Parser.onopentagend (/Users/thomasm/brandwatch/mission-control/node_modules/htmlparser2/lib/Parser.js:172:37)
    at Tokenizer._stateBeforeAttributeName (/Users/thomasm/brandwatch/mission-control/node_modules/htmlparser2/lib/Tokenizer.js:230:13)
    at Tokenizer._parse (/Users/thomasm/brandwatch/mission-control/node_modules/htmlparser2/lib/Tokenizer.js:658:9)
    at Tokenizer.write (/Users/thomasm/brandwatch/mission-control/node_modules/htmlparser2/lib/Tokenizer.js:632:7)
```

**Comment by cakuki** [comment]
Hey @tominbrighton,

Sorry for late response, notifications were off somehow. I tried your sample code and no error occurred. Maybe the source from remote url has changed until then.

Could you please confirm that this is not happening anymore so we can close the issue?
