### ISSUE TITLE
Exception Body is not RSS or ATom

### ISSUE THREAD

**Issue by slidenerd** [cakuki/feed-finder#3]
First of all, thank you for the fantastic work on this library, I was trying medium.com as the input and got this error
```

[ 'http://medium.com/osd.xml', 'http://www.medium.com/osd.xml' ]
D:\test\reader\index.js:35
            if (err) throw err;
                     ^

Error: Body is not RSS or ATOM
    at Request._callback (D:\test\reader\node_modules\feed-read\index.js:70:23)
    at Request.self.callback (D:\test\reader\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\test\reader\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\test\reader\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

Any ideas on how I can prevent this error in a live environment

**Comment by cakuki** [comment]
Hey @slidenerd, I am sorry to miss this. Somehow all notifications from Github was turned off. I have just tried same query but I haven't faced a problem. I guess the error occurs on your code cause the `osd.xml` files are not RSS or Atom files indeed.

So it seems that `osd.xml` files are false positive results. I will try to add more checks for this type of files. Probably on this weekend.

Thanks for reporting!
